import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { Form } from "./login_form";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    return (
        <>
            <Head>
                <title>Portopro</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <nav className="flex items-center justify-between flex-wrap p-6">
                    <div className="flex items-center flex-shrink-0 text-white mr-6">
                        <span className="font-semibold text-xl tracking-tight text-teal-500">
                            Portopro
                        </span>
                    </div>
                </nav>

                <div className="grid grid-cols-2 place-content-center">
                    <div className="">
                        <img
                            src="/images/undraw_Login_re_4vu2.png"
                            alt="Login Picture"
                        />
                    </div>
                    <div className="">
                        <Form />
                    </div>
                </div>
            </main>
        </>
    );
}
