import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { Form } from "./login_form";
import loginImage from "../../public/images/undraw_secure_login.svg";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    return (
        <>
            <Head>
                <title>Portopro</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <nav className="flex items-center justify-between flex-wrap p-6 mb-4">
                    <div className="flex items-center flex-shrink-0 text-white mr-6">
                        <span className="font-semibold text-xl tracking-tight text-primary">
                            Portopro
                        </span>
                    </div>
                </nav>

                <div className="flex place-content-end space-x-4">
                    <div className="w-0 sm:w-0 md:w-auto md:m-auto lg:w-auto lg:m-auto">
                        <Image
                            priority
                            src={loginImage}
                            alt="Follow us on Twitter"
                            height={640}
                            width={640}
                        />
                    </div>
                    <div className="basis-full sm:basis-full lg:basis-2/5 md:basis-full">
                        <Form />
                    </div>
                </div>
            </main>
        </>
    );
}
